const styles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  header: {
    background: "rgba(255, 255, 255, 0.98)",
    backdropFilter: "blur(10px)",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  headerContent: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "1rem 2rem",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "1rem",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  logo: {
    width: "50px",
    height: "50px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.8rem",
    fontWeight: "bold",
    borderRadius: "12px",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
  },
  brandInfo: {
    display: "flex",
    flexDirection: "column",
  },
  brandTitle: {
    fontSize: "1.3rem",
    color: "#667eea",
    fontWeight: 600,
    margin: 0,
  },
  brandSubtitle: {
    fontSize: "0.85rem",
    color: "#888",
    margin: 0,
  },
  navMenu: {
    display: "flex",
    gap: "2rem",
    alignItems: "center",
    flexWrap: "wrap",
  },
  navLink: {
    textDecoration: "none",
    color: "#555",
    fontWeight: 500,
    fontSize: "0.9rem",
    transition: "color 0.3s ease",
  },
  menuBtn: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    padding: "0.6rem 1.2rem",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.9rem",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.3)",
  },
  heroSection: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "3rem 2rem",
  },
  heroContent: {
    maxWidth: "1400px",
    margin: "0 auto",
  },
  greetingSection: {},
  greeting: {
    color: "white",
    fontSize: "2.5rem",
    fontWeight: 600,
    marginBottom: "1.5rem",
  },
  balanceInfo: {
    display: "flex",
    gap: "3rem",
    flexWrap: "wrap",
  },
  balanceItem: {
    background: "rgba(255, 255, 255, 0.2)",
    backdropFilter: "blur(10px)",
    padding: "1rem 2rem",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  balanceLabel: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: "0.95rem",
  },
  balanceAmount: {
    color: "white",
    fontSize: "1.3rem",
    fontWeight: 700,
  },
  actionButtons: {
    maxWidth: "1400px",
    margin: "-2rem auto 2rem",
    padding: "0 2rem",
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
  },
  actionBtn: {
    background: "white",
    color: "#667eea",
    border: "none",
    padding: "0.8rem 1.5rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.85rem",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
    transition: "all 0.3s ease",
  },
  statsGrid: {
    maxWidth: "1400px",
    margin: "0 auto 3rem",
    padding: "0 2rem",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "2rem",
  },
  statCard: {
    background: "white",
    padding: "2rem",
    borderRadius: "20px",
    boxShadow: "0 8px 30px rgba(0, 0, 0, 0.1)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
  },
  statIcon: {
    width: "70px",
    height: "70px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "2rem",
    marginBottom: "1rem",
  },
  successIcon: {
    background: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    color: "white",
  },
  failureIcon: {
    background: "linear-gradient(135deg, #eb3349 0%, #f45c43 100%)",
    color: "white",
  },
  pendingIcon: {
    background: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    color: "white",
  },
  purchaseIcon: {
    background: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    color: "white",
  },
  statTitle: {
    fontSize: "1rem",
    color: "#666",
    marginBottom: "0.5rem",
    fontWeight: 500,
  },
  statNumber: {
    fontSize: "2.5rem",
    fontWeight: 700,
    color: "#333",
    margin: 0,
  },
  dataSection: {
    maxWidth: "1400px",
    margin: "0 auto 3rem",
    padding: "0 2rem",
  },
  sectionHeader: {
    background: "white",
    padding: "1.5rem",
    borderRadius: "15px 15px 0 0",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
  },
  sectionTitle: {
    color: "#667eea",
    fontSize: "1.3rem",
    fontWeight: 600,
    margin: 0,
  },
  tableContainer: {
    background: "white",
    borderRadius: "0 0 15px 15px",
    overflow: "hidden",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  thead: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  th: {
    color: "white",
    padding: "1.2rem",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "0.9rem",
  },
  tr: {
    borderBottom: "1px solid #f0f0f0",
  },
  td: {
    padding: "1.2rem",
    color: "#555",
    fontSize: "0.9rem",
  },
  processBtn: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    padding: "0.8rem 2rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.3)",
    transition: "all 0.3s ease",
  },
  solveBtn: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    padding: "0.8rem 2rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
    marginTop: "1.5rem",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.3)",
    transition: "all 0.3s ease",
  },
  statusSolved: {
    padding: "0.4rem 1rem",
    borderRadius: "20px",
    fontSize: "0.85rem",
    fontWeight: 600,
    background: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    color: "white",
    display: "inline-block",
  },
  statusUnsolved: {
    padding: "0.4rem 1rem",
    borderRadius: "20px",
    fontSize: "0.85rem",
    fontWeight: 600,
    background: "linear-gradient(135deg, #eb3349 0%, #f45c43 100%)",
    color: "white",
    display: "inline-block",
  },
  footer: {
    background: "rgba(0, 0, 0, 0.8)",
    color: "white",
    textAlign: "center",
    padding: "1.5rem",
    marginTop: "auto",
  },
  footerText: {
    fontSize: "0.9rem",
    margin: 0,
  },
  footerStrong: {
    color: "#667eea",
  },
};

export default styles;