const styles = {
  container: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    minHeight: "100vh",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  header: {
    background: "white",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
  },
  headerContent: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "1rem 2rem",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  logo: {
    width: "50px",
    height: "50px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontSize: "1.5rem",
    fontWeight: "bold",
  },
  brandInfo: {
    display: "flex",
    flexDirection: "column",
  },
  brandTitle: {
    margin: 0,
    fontSize: "1.25rem",
    color: "#2d3748",
    fontWeight: "600",
  },
  brandSubtitle: {
    margin: 0,
    fontSize: "0.875rem",
    color: "#718096",
  },
  navMenu: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
    flexWrap: "wrap",
  },
  navItem: {
    position: "relative",
    display: "inline-block",
  },
  navLink: {
    color: "#4a5568",
    textDecoration: "none",
    fontSize: "0.875rem",
    fontWeight: "600",
    padding: "0.75rem 1rem",
    transition: "all 0.3s ease",
    cursor: "pointer",
    display: "block",
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: "0",
    backgroundColor: "white",
    minWidth: "220px",
    boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
    zIndex: 1000,
    opacity: 0,
    visibility: "hidden",
    transform: "translateY(-10px)",
    transition: "all 0.3s ease",
    borderRadius: "4px",
    overflow: "hidden",
  },
  dropdownItem: {
    display: "block",
    padding: "0.75rem 1rem",
    color: "#2d3748",
    textDecoration: "none",
    fontSize: "0.875rem",
    borderBottom: "1px solid #f0f0f0",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  menuBtn: {
    display: "none",
    background: "#667eea",
    color: "white",
    border: "none",
    padding: "0.5rem 1rem",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: "600",
  },
  heroSection: {
    padding: "3rem 2rem",
  },
  heroContent: {
    maxWidth: "1400px",
    margin: "0 auto",
  },
  greetingSection: {
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(10px)",
    borderRadius: "12px",
    padding: "2rem",
    color: "white",
  },
  greeting: {
    margin: "0 0 1.5rem 0",
    fontSize: "2rem",
    fontWeight: "600",
  },
  balanceInfo: {
    display: "flex",
    gap: "3rem",
    flexWrap: "wrap",
  },
  balanceItem: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  balanceLabel: {
    fontSize: "0.875rem",
    opacity: "0.9",
  },
  balanceAmount: {
    fontSize: "1.75rem",
    fontWeight: "700",
  },
  actionButtons: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "0 2rem 2rem 2rem",
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
  },
  actionBtn: {
    background: "white",
    color: "#667eea",
    border: "2px solid white",
    padding: "1rem 1.5rem",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 15px rgba(0,0,0,0.1)",
  },
  statsGrid: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "0 2rem 2rem 2rem",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "1.5rem",
  },
  statCard: {
    background: "white",
    borderRadius: "12px",
    padding: "2rem",
    boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
    transition: "all 0.3s ease",
    cursor: "pointer",
  },
  statIcon: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    marginBottom: "1rem",
    fontWeight: "bold",
  },
  successCard: { borderLeft: "4px solid #48bb78" },
  successIcon: { background: "#c6f6d5", color: "#48bb78" },
  failureCard: { borderLeft: "4px solid #f56565" },
  failureIcon: { background: "#fed7d7", color: "#f56565" },
  pendingCard: { borderLeft: "4px solid #ed8936" },
  pendingIcon: { background: "#feebc8", color: "#ed8936" },
  purchaseCard: { borderLeft: "4px solid #667eea" },
  purchaseIcon: { background: "#e9d8fd", color: "#667eea" },
  statTitle: {
    margin: "0 0 0.5rem 0",
    fontSize: "1rem",
    color: "#718096",
    fontWeight: "500",
  },
  statNumber: {
    margin: 0,
    fontSize: "2rem",
    color: "#2d3748",
    fontWeight: "700",
  },
  dataSection: {
    maxWidth: "1400px",
    margin: "0 auto 2rem auto",
    padding: "0 2rem",
  },
  sectionHeader: {
    background: "white",
    borderRadius: "12px 12px 0 0",
    padding: "1.5rem",
    borderBottom: "2px solid #e2e8f0",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1.25rem",
    color: "#2d3748",
    fontWeight: "600",
  },
  tableContainer: {
    background: "white",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  thead: {
    background: "#f7fafc",
  },
  th: {
    padding: "1rem",
    textAlign: "left",
    fontSize: "0.875rem",
    color: "#4a5568",
    fontWeight: "600",
    borderBottom: "2px solid #e2e8f0",
  },
  tr: {
    borderBottom: "1px solid #e2e8f0",
    transition: "all 0.2s ease",
  },
  td: {
    padding: "1rem",
    fontSize: "0.875rem",
    color: "#2d3748",
  },
  processBtn: {
    background: "#667eea",
    color: "white",
    border: "none",
    padding: "0.75rem 2rem",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  solveBtn: {
    background: "#667eea",
    color: "white",
    border: "none",
    padding: "1rem 2rem",
    borderRadius: "0 0 12px 12px",
    width: "100%",
    fontSize: "0.875rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  statusSolved: {
    background: "#c6f6d5",
    color: "#22543d",
    padding: "0.25rem 0.75rem",
    borderRadius: "12px",
    fontSize: "0.75rem",
    fontWeight: "600",
  },
  statusUnsolved: {
    background: "#fed7d7",
    color: "#742a2a",
    padding: "0.25rem 0.75rem",
    borderRadius: "12px",
    fontSize: "0.75rem",
    fontWeight: "600",
  },
  footer: {
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(10px)",
    padding: "2rem",
    textAlign: "center",
    marginTop: "2rem",
  },
  footerText: {
    margin: 0,
    color: "white",
    fontSize: "0.875rem",
  },
  footerStrong: {
    fontWeight: "700",
  },

   navContainer: {
    position: "relative",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: "40px",
  },
  navItem: {
    position: "relative",
    display: "inline-block",
  },
  button: {
    background: "#007bff",
    color: "#fff",
    border: "none",
    padding: "10px 18px",
    borderRadius: "5px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  dropdown: {
    position: "absolute",
    top: "40px",
    left: 0,
    backgroundColor: "#fff",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
    borderRadius: "6px",
    overflow: "hidden",
    zIndex: 10,
    width: "180px",
  },
  dropdownItem: {
    padding: "10px 15px",
    cursor: "pointer",
    borderBottom: "1px solid #eee",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 20,
  },
  popup: {
    background: "#fff",
    borderRadius: "8px",
    width: "360px",
    padding: "25px",
    textAlign: "center",
    boxShadow: "0 5px 15px rgba(0,0,0,0.3)",
    animation: "fadeIn 0.3s ease",
  },
  popupTitle: {
    marginBottom: "20px",
  },
  select: {
    width: "100%",
    padding: "8px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    outline: "none",
  },
  popupButtons: {
    marginTop: "20px",
    display: "flex",
    justifyContent: "space-between",
  },
  closeBtn: {
    background: "#dc3545",
    color: "white",
    border: "none",
    padding: "8px 15px",
    borderRadius: "5px",
    cursor: "pointer",
  },
  confirmBtn: {
    background: "#28a745",
    color: "white",
    border: "none",
    padding: "8px 15px",
    borderRadius: "5px",
    cursor: "pointer",
  },
  // Normal nav dropdowns
navDropdown: {
  position: "absolute",
  top: "100%",
  left: 0,
  backgroundColor: "#fff",
  minWidth: "220px",        // wider for long items
  boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
  zIndex: 1000,
  borderRadius: "4px",
  overflow: "hidden",
},

navDropdownItem: {
  display: "block",
  padding: "0.75rem 1rem",
  color: "#2d3748",
  textDecoration: "none",
  fontSize: "0.875rem",
  borderBottom: "1px solid #f0f0f0",
  transition: "all 0.2s ease",
  cursor: "pointer",
},

};

export default styles;
